repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.5.0
    hooks:
    -   id: markdownlint
        exclude: '^(?!_posts\/)'
