repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: |
            (?x)^(_posts/notebooks/.*)|(.*\.(ipynb))$
      - id: trailing-whitespace
        exclude: |
            (?x)^(_posts/notebooks/.*)$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        exclude: '^(?!_posts/markdown/)'
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.10.0
    hooks:
      - id: markdown-link-check
        exclude: '^(?!_posts/markdown/)'
        args: ["-c", ".markdown-link-check.json"]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-black
        additional_dependencies: [ black==22.3.0 ]
      - id: nbqa-isort
        additional_dependencies: [ isort==5.10.1 ]
      - id: nbqa-flake8
        additional_dependencies: [ flake8==4.0.1, flake8-bugbear==22.4.25 ]
  - repo: https://github.com/klieret/jekyll-relative-url-check
    rev: v2.0.1
    hooks:
      - id: jekyll-relative-url-check-html
      - id: jekyll-relative-url-check-markdown
