repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            static/datascience/.*|
            static/hacking/.*|
            static/productivity/.*|
            static/python/.*|
            static/work/.*
          )$
      - id: trailing-whitespace
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.10.0
    hooks:
      - id: markdown-link-check
        args: ["-c", ".markdown-link-check.json"]
  - repo: https://github.com/klieret/jekyll-relative-url-check
    rev: v2.0.1
    hooks:
      - id: jekyll-relative-url-check-html
        exclude: ^static/
      - id: jekyll-relative-url-check-markdown
        exclude: ^static/
