[redirects]
"/datascience/2018/08/21/AutoML.html" = "https://medium.com/georgian-impact-blog/choosing-the-best-automl-framework-4f2a90cb1826"
"/python/2019/08/08/Python-Tooling.html" = "https://medium.com/georgian-impact-blog/python-tooling-makes-a-project-tick-181d567eea44"
"/datascience/2021/04/08/Custom-Sklearn-Pipelines.html" = "https://web.archive.org/web/20250209105525/https://www.adithyabalaji.com/datascience/2021/04/08/Custom-Sklearn-Pipelines.html"
"/datascience/2021/05/17/Analyzing-Bird-Audio.html" = "https://web.archive.org/web/20250209122530/https://www.adithyabalaji.com/datascience/2021/05/17/Analyzing-Bird-Audio.html"
"/hacking/2021/08/10/Chipotle.html" = "/posts/chipotle/"
"/productivity/2021/11/20/Apple-Spoken-Content.html" = "/posts/apple-spoken-content/"
"/work/2021/12/18/Microsoft.html" = "/posts/microsoft/"
"/productivity/2022/02/01/Sleep.html" = "/posts/sleep/"
"/linktree.html" = "/lt/"
"/linktree/" = "/lt/"
